# Generated by Django 4.0.3 on 2022-04-09 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BranchMaster',
            fields=[
                ('BranchID', models.IntegerField(primary_key=True, serialize=False)),
                ('BranchName', models.CharField(max_length=200)),
                ('City', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProductMaster',
            fields=[
                ('ProductID', models.IntegerField(primary_key=True, serialize=False)),
                ('ProductName', models.CharField(max_length=200)),
                ('Category', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Price', models.IntegerField()),
                ('Quantity', models.IntegerField()),
                ('BranchID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductApp.branchmaster')),
                ('ProductID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductApp.productmaster')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrders',
            fields=[
                ('Date', models.DateField()),
                ('PurchaseOrderId', models.IntegerField(primary_key=True, serialize=False)),
                ('SupplierId', models.IntegerField()),
                ('OrderedQuantity', models.IntegerField()),
                ('ReceivedQuantity', models.IntegerField(blank=True, null=True)),
                ('OrderedDate', models.DateField()),
                ('ReceivedDate', models.DateField(blank=True, null=True)),
                ('BranchId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductApp.branchmaster')),
                ('ProductId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductApp.productmaster')),
            ],
        ),
    ]
